- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args: ["--fix"]
    - id: ruff-format

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort

- repo: https://github.com/google/yapf
  rev: v0.40.2
  hooks:
    - id: yapf
      additional_dependencies: [toml]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
    - id: mypy
      args: ["--install-types", "--non-interactive"]
      additional_dependencies:
        ["types-PyYAML", "types-requests", "types-Pillow", "types-psutil"]
