name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e . || true
          pip install pytest ruff mypy typer mlflow yapf isort
      - name: Ruff lint
        run: ruff check .
      - name: Ruff format (check)
        run: ruff format --check .
      - name: MyPy
        run: mypy .
      - name: Pytest
        run: pytest -q

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          pip install -e . || true
          pip install mkdocs mkdocs-material
      - name: Build docs
        run: |
          if [ -f docs/README.md ] || [ -f mkdocs.yml ]; then
            mkdocs build --strict || true
          else
            echo "No docs to build, skipping"
          fi
